# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rack-plastic"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wyatt Greene"]
  s.date = "2011-11-06"
  s.description = "\n      If you are creating Rack middleware that changes the HTML response, use\n      Rack::Plastic to get a head start.  Rack::Plastic takes care of the\n      boilerplate Rack glue so that you can focus on simply changing the HTML.\n    "
  s.email = "techiferous@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/plastic_helper.rb",
    "lib/plastic_test_helper.rb",
    "lib/rack-plastic.rb",
    "test/rack-plastic_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/techiferous/rack-plastic"
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = "1.8.10"
  s.summary = "Helps you write Rack middleware using Nokogiri."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["~> 1.0"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<rack>, ["~> 1.0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, ["~> 1.0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

